import { Pelicula } from "./modelo";

export const peliculasESDLA: Pelicula[] = [
    {
        titulo: "La comunidad del anillo",
        resumen: "El joven hobbit Frodo Bolsón recibe el Anillo Único y, acompañado por un grupo diverso de aliados, emprende un peligroso viaje para destruirlo y evitar que el malvado Sauron conquiste la Tierra Media. La misión está llena de desafíos y aventuras, poniendo a prueba su valor y amistad.",
        genero: "Acción",
        masVisto: true,
        calificacionImdb: 9.2,
        premioGalardon: true,
        fechaEstreno: new Date("2001-12-19"),
        imagen: "https://es.web.img3.acsta.net/medias/nmedia/18/89/67/45/20061512.jpg",
    },
    {
        titulo: "Las dos torres",
        resumen: "La comunidad del anillo se dispersa, y mientras Frodo y Sam continúan su peligrosa travesía hacia Mordor con la ayuda de Gollum, Aragorn, Legolas y Gimli unen fuerzas con el reino de Rohan para enfrentar la creciente amenaza del malvado Saruman. La batalla del abismo de Helm se convierte en un punto crucial en la lucha contra las fuerzas oscuras.",
        genero: "Acción",
        masVisto: true,
        calificacionImdb: 8.8,
        premioGalardon: true,
        fechaEstreno: new Date("2002-12-18"),
        imagen: "https://es.web.img3.acsta.net/medias/nmedia/18/89/85/69/20070008.jpg",
    },
    {
        titulo: "El retorno del rey",
        resumen: "Mientras Frodo y Sam se acercan a Mordor para destruir el Anillo Único, Aragorn lidera las fuerzas de los hombres en una épica batalla contra Sauron para distraerlo y dar a los hobbits una oportunidad de éxito. La culminación de sus esfuerzos determinará el destino de la Tierra Media.",
        genero: "Acción",
        masVisto: true,
        calificacionImdb: 9.7,
        premioGalardon: true,
        fechaEstreno: new Date("2003-12-17"),
        imagen: "https://es.web.img2.acsta.net/medias/nmedia/18/89/68/19/20061877.jpg",
    },
    {
        titulo: "Un viaje inesperado",
        resumen: "Bilbo Bolsón es reclutado por el mago Gandalf y un grupo de enanos para ayudarles a recuperar su reino de Erebor del dragón Smaug. En el camino, Bilbo descubre su propio valor y encuentra el Anillo Único, que cambiará el destino de la Tierra Media.",
        genero: "Aventuras",
        masVisto: true,
        calificacionImdb: 9,
        premioGalardon: true,
        fechaEstreno: new Date("2012-12-12"),
        imagen: "https://www.aceprensa.com/wp-content/uploads/2012/12/49051-0.jpg",
    },
    {
        titulo: "La desolación de Smaug",
        resumen: "Bilbo y los enanos continúan su viaje hacia la Montaña Solitaria, enfrentando peligros como los elfos del Bosque Negro y el hombre-oso Beorn. Al llegar, Bilbo confronta al temible dragón Smaug, desatando su furia sobre la Ciudad del Lago y poniendo en peligro a todos.",
        genero: "Aventuras",
        masVisto: true,
        calificacionImdb: 8.9,
        premioGalardon: true,
        fechaEstreno: new Date("2013-12-13"),
        imagen: "https://es.web.img3.acsta.net/pictures/13/12/13/11/42/576944.jpg",
    },
    {
        titulo: "La batalla de los cinco ejércitos",
        resumen: "La muerte de Smaug desata una lucha por el tesoro de Erebor entre enanos, elfos, hombres, y orcos. Bilbo debe navegar la creciente tensión y la batalla épica que se avecina, mientras se decide el destino de la Tierra Media.",
        genero: "Aventuras",
        masVisto: true,
        calificacionImdb: 9.1,
        premioGalardon: true,
        fechaEstreno: new Date("2014-12-16"),
        imagen: "https://es.web.img2.acsta.net/pictures/14/10/17/13/10/188874.jpg",
    },
];